// Generated by scripts/seo/generate-public-routes.mjs. Do not edit.
import type { PublicRoute } from "./route-types";

export const PUBLIC_ROUTES = [
  {"path":"/","priority":1,"changeFrequency":"daily"},
  {"path":"/privacy","priority":0.5,"changeFrequency":"monthly"},
  {"path":"/support","priority":0.6,"changeFrequency":"monthly"},
  {"path":"/terms","priority":0.5,"changeFrequency":"monthly"},
  {"path":"/tsn","priority":0.9,"changeFrequency":"monthly"},
] satisfies PublicRoute[];
