import { Connection, PublicKey, SystemProgram, Transaction, TransactionInstruction } from "@solana/web3.js";
import { TOKEN_PROGRAM_ID, getAssociatedTokenAddressSync } from "@solana/spl-token";
import { sha256 } from "@noble/hashes/sha2";
import { utf8ToBytes } from "@noble/hashes/utils";
import { Buffer } from "buffer";
import { VERIFIED_TSN_PROGRAM_ID } from "./program.js";
import { resolveSolanaRpcUrl } from "./rpc.js";

const MOTHER = utf8ToBytes("tsn_mother_escrow"); const EPOCH = utf8ToBytes("tsn_epoch_treasury"); const LEDGER = utf8ToBytes("tsn_epoch_ledger"); const AUTHORITY = utf8ToBytes("tsn_epoch_treasury_authority");
const concat = (parts: Uint8Array[]) => { const n = parts.reduce((a, b) => a + b.length, 0); const out = new Uint8Array(n); let p = 0; for (const b of parts) { out.set(b, p); p += b.length; } return out; };
const u64 = (n: bigint) => { const b = new Uint8Array(8); for (let i=0;i<8;i++) b[i]=Number((n >> (8n*BigInt(i)))&255n); return b; };
export const tsnInstructionDiscriminator = (name: string) => sha256(utf8ToBytes(`global:${name}`)).subarray(0, 8);
export function uiAmountToBaseUnits(amountUi: number | string, decimals: number) { const [w, f = ""] = String(amountUi).trim().split("."); if (!/^\d+$/.test(w) || !/^\d*$/.test(f) || f.length > decimals) throw new Error("invalid token amount"); return BigInt(w) * 10n ** BigInt(decimals) + BigInt((f + "0".repeat(decimals)).slice(0, decimals) || "0"); }
export function getEpochSettlementPdas(epochId: bigint | number, mint: string | PublicKey) { const programId = new PublicKey(VERIFIED_TSN_PROGRAM_ID); const motherEscrow = PublicKey.findProgramAddressSync([MOTHER], programId)[0]; const mintKey = new PublicKey(mint); const epoch = BigInt(epochId); const epochTreasury = PublicKey.findProgramAddressSync([EPOCH, motherEscrow.toBuffer(), Buffer.from(u64(epoch)), mintKey.toBuffer()], programId)[0]; const epochLedger = PublicKey.findProgramAddressSync([LEDGER, epochTreasury.toBuffer()], programId)[0]; const treasuryAuthority = PublicKey.findProgramAddressSync([AUTHORITY, epochTreasury.toBuffer()], programId)[0]; return { programId, motherEscrow, mint: mintKey, epochTreasury, epochLedger, treasuryAuthority, treasuryTokenAccount: getAssociatedTokenAddressSync(mintKey, treasuryAuthority, true) }; }
export async function fetchTsnSettlementEpoch(rpcUrl?: string) { const connection = new Connection(rpcUrl ?? resolveSolanaRpcUrl({ frontendSafe: false }), "confirmed"); const programId = new PublicKey(VERIFIED_TSN_PROGRAM_ID); const mother = PublicKey.findProgramAddressSync([MOTHER], programId)[0]; const a = await connection.getAccountInfo(mother, "confirmed"); if (!a || a.data.length < 145) throw new Error("TSN Mother Escrow is not initialized"); return Number(Buffer.from(a.data).readBigUInt64LE(137)); }
/** Funding creates no payment account, commitment PDA, or escrow keypair. */
export async function buildTsnSponsoredSettlementTransaction(params: { crankerFeePayer: string; senderWallet: string; tokenMintAddress: string; amountUi: number | string; tokenDecimals: number; epochId?: number; rpcUrl?: string; }) { const epochId = params.epochId ?? await fetchTsnSettlementEpoch(params.rpcUrl); const p = getEpochSettlementPdas(epochId, params.tokenMintAddress); const sender = new PublicKey(params.senderWallet); const senderTokenAccount = getAssociatedTokenAddressSync(p.mint, sender); const amount = uiAmountToBaseUnits(params.amountUi, params.tokenDecimals); if (amount <= 0n) throw new Error("amount must be positive"); const connection = new Connection(params.rpcUrl ?? resolveSolanaRpcUrl({ frontendSafe: false }), "confirmed"); const latest = await connection.getLatestBlockhash("confirmed"); const ix = new TransactionInstruction({ programId: p.programId, keys: [{pubkey:sender,isSigner:true,isWritable:true},{pubkey:p.motherEscrow,isSigner:false,isWritable:false},{pubkey:senderTokenAccount,isSigner:false,isWritable:true},{pubkey:p.mint,isSigner:false,isWritable:false},{pubkey:p.epochTreasury,isSigner:false,isWritable:true},{pubkey:p.epochLedger,isSigner:false,isWritable:true},{pubkey:p.treasuryAuthority,isSigner:false,isWritable:false},{pubkey:p.treasuryTokenAccount,isSigner:false,isWritable:true},{pubkey:new PublicKey("ATokenGPvbdGVxr1b2hvZbsiqW5xWH25efTNsLJA8knL"),isSigner:false,isWritable:false},{pubkey:TOKEN_PROGRAM_ID,isSigner:false,isWritable:false},{pubkey:SystemProgram.programId,isSigner:false,isWritable:false}], data: Buffer.from(concat([tsnInstructionDiscriminator("tsn_fund_epoch_treasury"),u64(BigInt(epochId)),u64(amount)])) }); const tx = new Transaction({feePayer:new PublicKey(params.crankerFeePayer),blockhash:latest.blockhash,lastValidBlockHeight:latest.lastValidBlockHeight}).add(ix); return { transactionBase64: tx.serialize({requireAllSignatures:false,verifySignatures:false}).toString("base64"), epochId, epochTreasury:p.epochTreasury.toBase58(), epochLedger:p.epochLedger.toBase58(), treasuryTokenAccount:p.treasuryTokenAccount.toBase58(), senderTokenAccount:senderTokenAccount.toBase58(), amountBaseUnits:amount.toString(), blockhash:latest.blockhash,lastValidBlockHeight:latest.lastValidBlockHeight }; }
