import fs from "node:fs";
import os from "node:os";
import path from "node:path";
import { createHash } from "node:crypto";
import { Connection, Keypair, PublicKey } from "@solana/web3.js";
import { decodeAssetEntry, deriveAssetAddresses, inspectAsset } from "../../tcap-protocol/scripts/tcap-asset-admin.mjs";

export const TCAP = new PublicKey("TcApT4CytBqvqEDpRYVB7Wfi6aFzmtSZdWvDsq6bp9x");
export const TSN = new PublicKey("TSN31jddtsmUg4D5aEdhY31nwB1e53VJJg9X8NoRP8V");
export const SPL = new PublicKey("TokenkegQfeZyiNwAJbNbGKPFXCWuBvf9Ss623VQ5DA");
export const DEVNET_RPC = process.env.TCAP_RPC_URL ?? process.env.ANCHOR_PROVIDER_URL ?? process.env.SOLANA_RPC_URL ?? "https://api.devnet.solana.com";
export const DEFAULTS = path.resolve(process.env.TCAP_DEVNET_DEFAULTS_FILE ?? "protocol-tests/tcap-credit-devnet.defaults.env");
export const seed = (value) => Buffer.from(value, "utf8");

function loadDefaults(file) {
  if (!fs.existsSync(file)) return;
  for (const raw of fs.readFileSync(file, "utf8").split(/\r?\n/)) {
    const line = raw.trim();
    if (!line || line.startsWith("#")) continue;
    const match = line.match(/^([A-Z][A-Z0-9_]*)=(.*)$/);
    if (match && process.env[match[1]] === undefined) process.env[match[1]] = match[2].trim().replace(/^(['"])(.*)\1$/, "$2");
  }
}
loadDefaults(DEFAULTS);

export function parseOptions(argv) {
  const options = {};
  for (const item of argv) {
    if (!item.startsWith("--")) continue;
    const [key, ...rest] = item.slice(2).split("=");
    options[key] = rest.length ? rest.join("=") : true;
  }
  return options;
}

export function connection() { return new Connection(DEVNET_RPC, "confirmed"); }
export function redactRpc(url) { return String(url).replace(/([?&](?:api[-_]?key|token|secret)=)[^&]+/gi, "$1[REDACTED]"); }
export function keypairPath(options = {}) {
  const explicit = options["governance-keypair"] ?? process.env.TCAP_GOVERNANCE_KEYPAIR;
  const wallet = process.env.TCAP_GOVERNANCE_WALLET;
  if (!explicit && wallet) {
    try {
      new PublicKey(wallet);
      throw new Error("TCAP_GOVERNANCE_WALLET_ADDRESS_ONLY: public address cannot sign; also set TCAP_GOVERNANCE_KEYPAIR to the matching secret keypair");
    } catch (error) {
      if (String(error?.message).startsWith("TCAP_GOVERNANCE_WALLET_ADDRESS_ONLY:")) throw error;
    }
  }
  const selected = explicit
    ?? process.env.TCAP_GOVERNANCE_WALLET
    ?? process.env.SOLANA_WALLET
    ?? path.join(os.homedir(), ".config/solana/id.json");
  return selected.startsWith("~/") ? path.join(os.homedir(), selected.slice(2)) : selected;
}
export function loadKeypair(file) {
  if (!fs.existsSync(file)) throw new Error(`MISSING_GOVERNANCE_KEYPAIR: ${file} does not exist; set TCAP_GOVERNANCE_KEYPAIR or pass --governance-keypair`);
  try {
    const signer = Keypair.fromSecretKey(Uint8Array.from(JSON.parse(fs.readFileSync(file, "utf8"))));
    if (process.env.TCAP_GOVERNANCE_WALLET) {
      try {
        const expected = new PublicKey(process.env.TCAP_GOVERNANCE_WALLET);
        if (!expected.equals(signer.publicKey)) throw new Error(`TCAP_GOVERNANCE_WALLET_MISMATCH: address ${expected.toBase58()} does not match supplied keypair ${signer.publicKey.toBase58()}`);
      } catch (error) {
        if (String(error?.message).startsWith("TCAP_GOVERNANCE_WALLET_MISMATCH:")) throw error;
      }
    }
    return signer;
  }
  catch (error) {
    if (String(error?.message).startsWith("TCAP_GOVERNANCE_WALLET_MISMATCH:")) throw error;
    throw new Error("INVALID_GOVERNANCE_KEYPAIR: expected a Solana 64-byte JSON keypair; private bytes are never logged");
  }
}
export function digest(label) { return createHash("sha256").update(label).digest("hex"); }
export function assetForMint(mint) { return deriveAssetAddresses(mint, SPL); }
export async function inspect(connectionValue, mint) { return inspectAsset(connectionValue, mint, SPL.toBase58()); }
export function requireCurrentAsset(asset) {
  if (!asset.assetEntry?.exists || asset.assetEntry.dataBytes < 287 || asset.assetEntry.version !== 1) throw new Error("LEGACY_OR_TRUNCATED_ASSET_ENTRY: current TcapAssetEntryV1 is required");
  if (!asset.governancePolicy?.exists || !asset.extensionPolicy?.exists) throw new Error("MISSING_V2_POLICY_ACCOUNTS: run network:init-asset with TCAP governance");
}
export function envValue(name, fallback = "") {
  const text = fs.existsSync(DEFAULTS) ? fs.readFileSync(DEFAULTS, "utf8") : "";
  return text.match(new RegExp(`^${name}=(.*)$`, "m"))?.[1] ?? fallback;
}
export function writeDefaults(values) {
  const lines = ["# Live, non-secret Devnet TCAP credit defaults. Generated by network:set-defaults.", ...Object.entries(values).map(([key, value]) => `${key}=${value}`), ""];
  const dir = path.dirname(DEFAULTS); fs.mkdirSync(dir, { recursive: true });
  const temp = `${DEFAULTS}.${process.pid}.tmp`; fs.writeFileSync(temp, lines.join("\n"), { encoding: "utf8", mode: 0o600 }); fs.renameSync(temp, DEFAULTS);
}
